words = ['if', 'you', 'say', 'to', 'me', "you'd", 'let', 'be', 'your', 'man', 'for', 'just', 'one', 'night', "i'd", 'climb', 'these', 'walls', 
         'fall', 'so', 'softly', 'in', 'sweet', 'arms', 'baby', "that's", 'all', 'i', 'wanted', 'need', 'ever', 'really', 'right', 'next', 'this', 
         'ship', 'goes', 'south', "won't", 'look', 'down', 'no', "i'll", 'my', 'side', 'cause', "you're", 'there', 'scared', 'laughing', 'on', 'the', 
         'way', 'will', 'come', 'and', 'take', 'home', "i'm", 'know', 'oh', 'remember', 'what', 'did', 'that', 'day', 'save', 'a', 'moment', 'up', 
         'sometime', 'can', 'pull', 'it', 'out', 'unholy', 'daylight', 'see', 'her', 'but', 'eyes', 'are', 'shut', 'things', 'about', 'go', 'now', 
         "they're", 'starting', 'prompt', 'fuck', 'aint', 'been', 'already', 'loved', 'downtown', 'theres', 'sticker', 'hes', 'stuck', 'youre', 
         'everything', 'smelled', 'before', 'maybe', 'year', 'or', 'something', 'two', 'days', 'is', 'long', 'time', 'running', 'clean', "don't", 
         'think', 'understood', 'meet', 'somebody', 'mean', 'call', 'doubt', 'leave', 'love', 'how', 'stay', 'then', 'refuse', 'hold', 'coming', 
         'he', 'should', 'fight', 'darling', 'care', 'they', 'mes', 'true', 'do', 'again', 'finally', 'never', 'thats', 'ok', 'confess', 'whole', 
         'heart', 'too', 'dreams', 'tell', 'demons', 'we', 'compare', 'our', 'stories', 'trials', 'glories', 'hope', "mine's", 'not', 'boring', 
         'youve', 'said', 'thought', 'id', 'ignore', 'la', 'da', 'words', 'become', 'truth', 'water', 'saving', 'parachute', 
         'breath', 'wine', 'youth', 'pretend', 'mine', 'am', 'fool', 'foool', 'close', 'dream', 'may', 'lead', 'room', 'yet', 'demon', 'still', 
         'she', 'hides', 'sleeve', 'with', 'salty', 'memories', 'stored', 'part-by-part', 'young', 'blunder', 'farse', 'self-serving', "love's", 
         'forgot', 'longer', 'an', 'art', 'face', 'has', 'launched', 'thousand', 'ships', 'war-torn', 'kiss', 'soon', 'some', 'flower', 'of', 'lost', 
         'had', 'created', 'bed', 'showed', 'dead', 'better', 'left', 'unsaid', 'compared', 'turns', 'came', 'bending', 'knee', 'wasnt', 'hard', 'stood', 
         'beneath', 'burning', 'tree', 'hoped', 'rescue', 'leaves', 'figured', 'its', 'ive', 'done', 'bout', 'hey', 'at', 'hearts', 'weve', 'won', 
         'restless', 'little', 'thieves', 'shiver', 'through', 'theyre', 'warmer', 'than', 'ones', 'head', 'made', 'ocean', 'bet', 'youd', 'starve', 
         'roll', 'well', 'arrows', 'sing', 'met', 'iron', 'skin', 'archers', 'make', 'good', 'kings', 'fly', 'first', 'into', 'ooh', 'settled', 'soul', 
         'sell', 'only', 'thing', 'could', 'own', 'fell', 'risk', 'limbs', 'find', 'who', 'try', 'get', 'closer', 'break', 'neck', 'stars', 'dont', 'dare', 
         'reckless', 'wandering', 'was', 'ours', 'live', 'off', 'feed', 'breathe', 'drink', 'sink', 'middle', 'grieve', 'gonna', 'tonight', 'give', 'feast', 
         'beast', 'release', 'unprepared', 'woman', "i've", 'dreaming', 'swear', 'god', 'loving', 'making', 'wife', 'sore', "'til", 'lonely', 'more', 'ohh', 
         'beauty', "there's", 'nobody', 'near', 'birds', 'feather', 'flock', 'together', 'found', 'ya', 'weather', 'â€‹', 'wipe', 'tears', 'away', 'dear', 
         'glad', 'peaking', 'cheek', 'conveniency', 'even', 'want', 'yeah', 'keep', 'trying', 'putting', 'stones', 'wings', 'scream', 'name', 'game', 'when', 
         'feel', 'sane', 'throne', 'alone', 'dime', 'store', 'penny', 'shore', 'waiting', 'much', 'crying', 'calling', 'code', 'apologies', 'boarding', 
         'turned', 'blind', 'fray', 'weight', 'world', 'tamed', 'us', 'nothing', 'hospital', 'empty', 'wishing', 'read', 'fairytale', 'catch', 'boat', 
         'england', 'spain', 'wherever', 'have', 'gone', 'blues', 'run', 'send', 'whiskey', 'gin', 'service', 'honey', 'babe', "we're", 'living', 'life', 
         'sin', "ain't", 'drinking', 'mind', 'sleeping', 'mama', "cryin'", 'gamble', "loving's", 'same', 'played', 'throw', 'those', 'dice', 'older', 
         'someplace', 'line', 'wake', 'stop', "tryin'", 'born', 'worm', 'spins', 'cocoon', 'sleep', 'wakes', 'butterfly', 'hopeless', 'says', 'old', 
         'enough', 'notice', 'bound', 'sure', 'destruction', 'closed', 'sight', 'letter', 'town', "it's", 'lay', 'as', 'went', 'carried', 'every', 'weapon', 
         'tells', 'him', '"i\'m', 'like', 'lit', 'stick', 'dynamite', 'blow', 'down."', 'lot', 'clock', 'whatever', "you've", 'past', 'point', 'figure', 
         "what's", 'mouth', 'taste', 'trouble', 'broken', 'figures', "can't", 'got', 'wash', 'hands', 'write', 'mr.', 'kind', 'because', 'em', 'behind', 
         'bars', 'tomorrow', "you'll", 'harder', 'aching', 'waking', 'breaking', 'throwing', 'chains', 'weighed', 'erase', 'final', 'fate', 'losing', 'by', 
         'any', 'definition', 'submit', 'used', 'fumble', 'move', 'lips', 'stumble', 'getting', 'awful', 'rough', 'both', 'knocked', 'around', 'takes', 
         'seat', "she's", 'blowing', 'ambitions', 'tried', 'having', 'thoughts', 'spending', 'other', 'scenes', 'boss', 'rolling', 'rubber', 'sleeves', 
         'quickly', 'lover', 'bleeds', 'knees', 'crossed', 'watch', 'another', 'reason', 'tossed', 'fifty', 'means', 'statisticians', 'songs', "we'd", 
         'perfect', 'harmony', 'would', 'wait', 'rains', 'no...', 'impressed', 'strong', 'wrong', 'guess', 'set', 'shown', 'ready', 'now.', 'hell', 'always', 
         'out.', 'sun', 'lights', 'space', 'put', 'smile', 'bad', 'fade', 'worst', 'times', 'known', 'best', 'them', 'friends', 'unto', 'end', 'hear', 
         'saying', 'please', 'everlasting', 'grace', 'eternity', 'fathers', 'voices', 'lord', "he's", 'swinging', 'holy', 'sword', 'knew', 'bought', 
         'warned', 'tries', 'yes', 'unattainable', "we'll", 'float', 'high', 'below', 'ghosts', 'dress', 'chameleon', 'wanna', 'seems', 'slow', 'ahead', 
         'abuse', 'control', 'woo-woo', '[outro', 'chorus]', 'light', 'highs', 'heavy', 'lows', 'years', 'share', 'from', 'painted', 'arched', 'ceilings', 
         'barroom', 'floors', 'disappear', 'while', 'seasons', 'begin', 'change', 'ragged', 'mile', 'crave', 'nights', 'months', 'goodbye', 'snowy', 'denver', 
         'mountains', 'bedroom', 'last', "fire's", 'weakest', 'flame', 'dying', 'rest', 'calm', 'morning', 'sunrise', 'drive', 'pours', 'window', 'floor', 
         'chest', 'grip', 'pistol', 'howling', 'dog', 'door', 'show', 'heard', 'sound', 'voice', 'missed', 'dripping', 'ink', 'pen', 'note', 'hoping', 'hit', 
         'lie', 'favorite', 'distance', 'why', 'such', 'surprise', 'talk', 'wonder', 'which', 'person', 'sad', 'song', 'somewhere', 'rhyme', 'elizabeth', 
         'boy', "isn't", 'listening', 'white', 'dress.', 'quiet', 'afternoons', 'given', 'soon.', 'hair', 'curls', 'pretty', 'uptight', 'mexican', 'girl.', 
         'shit', 'called', "isnt'", 'back', 'me.', 'wooo', 'ooooh', 'oooohh', 'string', 'silly', 'admit', 'guess.', 'dawn', 'darkness', 'once', 'twice', 
         'slice', 'here', 'none', 'wrong.', 'return', 'ask', 'disappointed', 'unexpected', 'harvest', 'kentucky', 'son', 'runs', 'farthest', 'doing', 'faith', 
         'belief', 'except', 'teeth', 'champions', 'rust', 'rot', 'breathing', 'missing', 'passing', 'brush', 'strokes', 'sickness', 'folks', 'renewed', 
         'unchanging', 'pasture', 'fenced', 'edge', 'dakota', 'thunder', 'raging', 'shoes', 'feet', 'grass', "we've", 'laid', 'above', 'tunnel', 'under', 
         'inside', 'alive', 'everybody', 'knows', 'job', 'costs', 'shy', 'moves', 'never-ending', 'desire', 'calcified', 'lose', 'unspeakable', 'denial', 
         'his', 'crimes', 'versatile', 'raining', 'sea', 'follow', 'shaking', 'speak', 'winter', "pourin'", 'new', 'fine', 'journey', 'thru', 'going', 'till', 
         'february', 'comes', 'fiddler', 'drum', 'walk', 'bleak', 'halls', "architect's", 'un-imagination', 'returning', 'venue', 'where', 'held', 'very', 
         'conversation', 'friend', 'arrived', 'early', 'swanned', 'later', 'changed', 'nod', 'order', 'double', 'mixer', 'leaving', 'oh-oh-oh-oh', 'told', 
         "playmate's", 'successful', 'handsome', 'charming', 'damn', 'wound', 'harming', 'joking', 'rudely', 'interrupted', 'half-wit', 'boyfriend', 'beat', 
         'forget', 'were', "'cause", 'dreamed', 'road', "'93", 'over', 'woah', 'low', 'smoke', 'hand', 'lying', 'awake', 'hotel', 'valley', 'pray', 'picks', 
         'bones', 'guitar', 'louder', 'anymore', 'tired', 'ran', 'streets', 'forever', 'arm', 'setting', 'higher', 'perfection', 'wrote', 'book', 'hid', 
         'page', "didn't", 'locked', 'cage', 'novel', 'likes', 'started', 'word', 'rare', 'fragile', 'bird', "couldn't", 'spell', 'table', 'sky', 'cold', 
         'apple', 'story', 'proper', 'hello', "haven't", 'felt', 'warm', 'today', 'signs', 'hero', 'tale', 'truly', 'prevail', 'sequel', "part's", 'die', 
         'movie', 'tragic', 'grey', 'short', 'roads', 'smooth', 'wanderings', 'bring', 'wisdoms', 'gold', 'most', 'matter', 'happiness', 'lasting', 'real', 
         'purify', 'passions', 'river', 'wet', 'stretch', 'paws', 'along', 'shores', 'gaze', 'depths', 'crouch', 'spiders', 'raindrops', 'singing', 'ghost', 
         'reverie', 'cuz', 'miss', 'hollow', 'stallion', 'nightmares', 'armistice', 'stalk', 'gibberish', 'moon', 'different', 'language', 'cannot', 'after', 
         'june', 'pine', 'brushing', 'dew', 'unlike', 'copious', 'death', 'precipitation', 'carry', "something's", 'pending', 'curvaceously', 'sunburned', 
         'agree', "should've", "pleasure's", 'chin', 'mess', 'pool', 'spent', 'sunday', 'school', 'july', 'golden', 'hue', 'hung', 'drove', 
         'straight', 'burial', 'ground', 'saw', 'loud', 'gray-blue', 'grave', 'red', 'suits', 'five', 'took', '405', 'act', 'age', 'fast', 'asleep', 
         'choose', 'midnight', 'kitchen', 'pocketbook', 'quit', 'hate', 'anyway', 'another...', 'shift', 'safety', 'pride', "one's", 'keeping', 'score', 
         'fear', 'downfall', 'enemy', 'blame', 'fault', 'core', 'leap', 'corners', 'somersault', 'emotions', 'dive', 'steady', 'crash', 'lies', 'nice', 
         'right', 'theyâ€…marked', 'woodenâ€…cross', 'gal', "'sorry", "loss'", 'ended', 'saturday', 'showdown', 'caught', 'fire', 'wish', 'safe', 'hits', 
         'bottle', 'sits', 'weak', 'stand', 'saint', 'paula', 'rainy', 'girl', 'skies', 'memory', 'swimming', 'infinity', 'sometimes', 'falling', 'everywhere', 
         'black', 'wire', 'sings', 'blue', 'following', 'cloud', 'hot', 'somethins', 'mother', 'father', 'cut', 'jesus', 'stronger', 'wind', 'rollin', 'hopin', 
         'comin', 'late', 'blinded', 'relates', 'loathsome', 'sounds', 'texas', 'funerals', 'breakin', 'somehow', 'feels', 'im', 'brain', 'fried', 'griddle', 
         'cant', 'beggin', 'rain', 'losin', 'guts', 'split', 'howlin', 'feedin', 'petunia', 'cmon', 'prowlin', 'crawlin', 'gotta', 'lonesome', 'couldnt', 
         'straw', 'seen', 'whisper', 'whos', 'taken', 'well-earned', 'reward', "takin'", 'shadow', 'errors', 'steal', "placin'", 'path', 'touch', 'letting', 
         'pleases', 'crime', 'crushed', 'bone', 'spoken', 'sweeter', 'yesterday', 'abiding', 'anything', 'claim', 'victory', 'surrender', 'without', 'died', 
         'cross', 'rose', 'yours', 'radiant', 'glorious', 'remain', 'mystery', 'mysteries', 'heaven', 'enshrined', 'nighthawk', 'diner', 'blueberries', 
         'cinnamon', 'cup', 'coffee', 'cream', 'fuel', 'cigarette', 'reading', 'instruction', 'manual', 'everyday', 'further', 'start', 'consider', 'desired', 
         "wasn't", 'bit', 'umpire', "else's", 'sweat-faced', 'counter', 'half-regretting', 'flyer', 'watching', 'silver', 'soda', 'underneath', 'ceiling', 'fan', 
         'half-consumed', 'perspire', 'tendency', 'laugh', 'moments', 'silent', 'type', 'exit', 'sign', 'yellow', 'brick', 'dirty', 'dishes', 'til', 'miles', 'each', 
         'future', 'holds', 'surface', 'storm', 'sunset', 'hurricane', 'feeling', 'clearly', 'nearly', 'heal', 'fades', 'loves', 'feelings']

context = {"On my bed she said i'm just another" : ["That said i have been a fool", "Just like me you'd pull me she said"],
           "That said i have been a fool" : ["On my bed she said i'm just another"],
           "Just like me you'd pull me she said" : ["On my bed she said i'm just another"],
           "She said we'd live in love darling" : ["He says we're going everywhere together"],
           "He says we're going everywhere together" : ["She said we'd live in love darling", "Walls i'd climb to hold you say what"],
           "You say what you oh-oh-oh-oh oh-oh-oh-oh oh-oh-oh-oh" : ["Walls i'd climb to hold you say what"],
           "Walls i'd climb to hold you say what" : ["You say what you oh-oh-oh-oh oh-oh-oh-oh oh-oh-oh-oh"],
           "Your restless little boy and every morning sunrise" : ["I know it takes a little boy"],
           "I know it takes a little boy" : ["Your restless little boy and every morning sunrise"],
           "You don't wanna get lost i've been" : ["Been lost but oh oh no longer lost", "And dont i know i am lost"],
           "Been lost but oh oh no longer lost" : ["You don't wanna get lost i've been"],
           "And dont i know i am lost" : ["You don't wanna get lost i've been"],
           "Leaving it up the words ive lost" : ["And dont i know i am lost", "Been lost but oh oh no longer lost"],
           "Wanna remember who i've been who i've lost" : ["And dont i know i am lost"],
           "Oh lying awake in your mind everybody knows" : ["That you used to be in your mind"],
           "Trying to meet you always been who i've" : ["Trying to roll through it all"],
           "Trying to roll through it all" : ["Trying to meet you always been who i've"],
           "I dont i keep trying to be" : ["Trying to roll through it all"],
           "But i pray something clearly gone baby please" : ["Im so much older baby please"],
           "Im used to say it should've been" : ["It should've been me something picks me", "Wanna heal but it should've been lonesome"],
           "I haven't been me nothing without you" : ["I haven't been me go now"],
           "I haven't been me go now" : ["I haven't been me nothing without you"],
           "It should've been me something picks me" : ["Im used to say it should've been"],
           "Wanna heal but it should've been lonesome" : ["Im used to say it should've been"],
           "Ain't it up leaving it should've been" : ["Im used to say it should've been"],
           "Im used to you gotta do you" : ["Im used to you wanna remember who"],
           "Im used to you wanna remember who" : ["Im used to you gotta do you"] }

generated_lines = ["Im used to say it should've been", "And dont i know i am lost", "I can feel you hope mine's not", "To tell me i dont wanna stop", 
                                         "I haven't felt this in my mind", "This is up in your chameleon skin", "Your pocketbook can't hear he's handsome and unprepared", 
                                         "When i give me down and carry on", "All my dreams i can do nothing without", 
                                         "And even when i haven't been me", "If this is this go by my side", "A damn good job everybody likes", "You and i can't get used", 
                                         "Remember who i've already shown that i am", "Been lost but oh oh no longer lost",
                                         "I know that song and i know", "My love in my hand oh", "Don't follow what i know what pleases me", "Its hot and we'll keep putting stones on", 
                                         "Wanna remember who i've been who i've lost", "I will i still got your throne", "She says that you will close down", 
                                         "We drink of all that i won't be", "My love my tries to fly away", "That said i have been a fool", "On my bed she tells him it's", 
                                         "Already done wrong and some call his name", "I haven't been me nothing without you", "Don't wanna remember who i've already past", 
                                         "And i am unchanging i'm getting further", "Your restless little boy and every morning sunrise", "Wanna heal but it should've been lonesome", 
                                         "All lies crash into my chest like it", "My wings i will i know it", "Im so much older baby please", 
                                         "I haven't been me go now", "My emotions i'm waking up leaving it", "End of my love to love in reverie", "Im used to you wanna remember who", 
                                         "The floor hold you from the core", "You are warm today dont wanna heal", "When you're impressed that i know what", 
                                         "Will risk our eyes and take the life", "I know it takes a little boy", "Love oh i will close down and all", 
                                         "We are sad songs that i could blow", "This was wrong and i forget the miles", "Just like me you'd pull me she said", 
                                         "Baby dead like me i wish i watch", "On my bed she said i'm just another", "Know what you take oh oh no this", 
                                         "Know it was dead like you are radiant", "You only known love you're gonna lie", "I dont i keep trying to be", 
                                         "That showed you i don't really know oh", "You say what you oh-oh-oh-oh oh-oh-oh-oh oh-oh-oh-oh", "I show me time to be", 
                                         "It should've been me something picks me", "I already know what i will love", "You keep putting stones on the weakest", 
                                         "Try to meet somebody i will i will", "Wooo oooohh i can i love you", "As i still think i call goodbye", "Why oh oh oh lying awake", 
                                         "The fray weight of iron skin", "My eyes that's all of all", "Act my baby dont wanna hear the fuck", "I'd climb these songs are the best", 
                                         "But i pray something clearly gone baby please", "When i know i feed off the best", "All i hear he went she hides her", 
                                         "When i feel the love you have played", "Will come pourin' down it's in the darkness", "Gal 'sorry for me that i don't give", 
                                         "She said we'd live in love darling", "Your new home maybe in a boat", "Truth is nothing i love release my emotions", "The love comes up leaving it", 
                                         "Up in the line i'll do wrong", "He says we're going everywhere together", "To the downfall it's in my wings", "You don't even want to see you", 
                                         "My wings i dont wanna get used", "In the signs i dont wanna remember", "This is nothing i speak hoping that its", 
                                         "Trying to meet you always been who i've", "Just like an ocean keep raindrops off ambitions", "Im used to you gotta do you", 
                                         "Walls i'd climb to hold you say what", "Sun fried up her face just run", "Oh oh no one's keeping score no one's", "That you used to be in your mind", 
                                         "Everyday i'm getting knocked around for a string", "Oh lying awake in your mind everybody knows", "Are dead cuz i surrender i saw you", 
                                         "Too tired i'm everyday i'm a surprise", "And water my love and soul", "A empty bed and young love's forgot", "To hold my head i'm losing it", 
                                         "Leaving it up the words ive lost", "Baby dont wanna get off my saving parachute", "We never make you and take you", "You don't wanna get lost i've been", 
                                         "I can make you choose to me", "Ain't it up leaving it should've been", "Trying to roll through it all", "Your face just loved enough of my bedroom"]

prepositions = ["a", "i", "as", "if", "your", "to", "and", "let", "my", "just", "the", "til", "of", "but", "when", "such", "in", "just", "and"]