words = ['if', 'you', 'say', 'to', 'me', "you'd", 'let', 'be', 'your', 'man', 'for', 'just', 'one', 'night', "i'd", 'climb', 'these', 'walls', 
         'fall', 'so', 'softly', 'in', 'sweet', 'arms', 'baby', "that's", 'all', 'i', 'wanted', 'need', 'ever', 'really', 'right', 'next', 'this', 
         'ship', 'goes', 'south', "won't", 'look', 'down', 'no', "i'll", 'my', 'side', 'cause', "you're", 'there', 'scared', 'laughing', 'on', 'the', 
         'way', 'will', 'come', 'and', 'take', 'home', "i'm", 'know', 'oh', 'remember', 'what', 'did', 'that', 'day', 'save', 'a', 'moment', 'up', 
         'sometime', 'can', 'pull', 'it', 'out', 'unholy', 'daylight', 'see', 'her', 'but', 'eyes', 'are', 'shut', 'things', 'about', 'go', 'now', 
         "they're", 'starting', 'prompt', 'fuck', 'aint', 'been', 'already', 'loved', 'downtown', 'theres', 'sticker', 'hes', 'stuck', 'youre', 
         'everything', 'smelled', 'before', 'maybe', 'year', 'or', 'something', 'two', 'days', 'is', 'long', 'time', 'running', 'clean', "don't", 
         'think', 'understood', 'meet', 'somebody', 'mean', 'call', 'doubt', 'leave', 'love', 'how', 'stay', 'then', 'refuse', 'hold', 'coming', 
         'he', 'should', 'fight', 'darling', 'care', 'they', 'mes', 'true', 'do', 'again', 'finally', 'never', 'thats', 'ok', 'confess', 'whole', 
         'heart', 'too', 'dreams', 'tell', 'demons', 'we', 'compare', 'our', 'stories', 'trials', 'glories', 'hope', "mine's", 'not', 'boring', 
         'youve', 'said', 'thought', 'id', 'ignore', 'la', 'da', 'words', 'become', 'truth', 'water', 'saving', 'parachute', 
         'breath', 'wine', 'youth', 'pretend', 'mine', 'am', 'fool', 'foool', 'close', 'dream', 'may', 'lead', 'room', 'yet', 'demon', 'still', 
         'she', 'hides', 'sleeve', 'with', 'salty', 'memories', 'stored', 'part-by-part', 'young', 'blunder', 'farse', 'self-serving', "love's", 
         'forgot', 'longer', 'an', 'art', 'face', 'has', 'launched', 'thousand', 'ships', 'war-torn', 'kiss', 'soon', 'some', 'flower', 'of', 'lost', 
         'had', 'created', 'bed', 'showed', 'dead', 'better', 'left', 'unsaid', 'compared', 'turns', 'came', 'bending', 'knee', 'wasnt', 'hard', 'stood', 
         'beneath', 'burning', 'tree', 'hoped', 'rescue', 'leaves', 'figured', 'its', 'ive', 'done', 'bout', 'hey', 'at', 'hearts', 'weve', 'won', 
         'restless', 'little', 'thieves', 'shiver', 'through', 'theyre', 'warmer', 'than', 'ones', 'head', 'made', 'ocean', 'bet', 'youd', 'starve', 
         'roll', 'well', 'arrows', 'sing', 'met', 'iron', 'skin', 'archers', 'make', 'good', 'kings', 'fly', 'first', 'into', 'ooh', 'settled', 'soul', 
         'sell', 'only', 'thing', 'could', 'own', 'fell', 'risk', 'limbs', 'find', 'who', 'try', 'get', 'closer', 'break', 'neck', 'stars', 'dont', 'dare', 
         'reckless', 'wandering', 'was', 'ours', 'live', 'off', 'feed', 'breathe', 'drink', 'sink', 'middle', 'grieve', 'gonna', 'tonight', 'give', 'feast', 
         'beast', 'release', 'unprepared', 'woman', "i've", 'dreaming', 'swear', 'god', 'loving', 'making', 'wife', 'sore', "'til", 'lonely', 'more', 'ohh', 
         'beauty', "there's", 'nobody', 'near', 'birds', 'feather', 'flock', 'together', 'found', 'ya', 'weather', 'â€‹', 'wipe', 'tears', 'away', 'dear', 
         'glad', 'peaking', 'cheek', 'conveniency', 'even', 'want', 'yeah', 'keep', 'trying', 'putting', 'stones', 'wings', 'scream', 'name', 'game', 'when', 
         'feel', 'sane', 'throne', 'alone', 'dime', 'store', 'penny', 'shore', 'waiting', 'much', 'crying', 'calling', 'code', 'apologies', 'boarding', 
         'turned', 'blind', 'fray', 'weight', 'world', 'tamed', 'us', 'nothing', 'hospital', 'empty', 'wishing', 'read', 'fairytale', 'catch', 'boat', 
         'england', 'spain', 'wherever', 'have', 'gone', 'blues', 'run', 'send', 'whiskey', 'gin', 'service', 'honey', 'babe', "we're", 'living', 'life', 
         'sin', "ain't", 'drinking', 'mind', 'sleeping', 'mama', "cryin'", 'gamble', "loving's", 'same', 'played', 'throw', 'those', 'dice', 'older', 
         'someplace', 'line', 'wake', 'stop', "tryin'", 'born', 'worm', 'spins', 'cocoon', 'sleep', 'wakes', 'butterfly', 'hopeless', 'says', 'old', 
         'enough', 'notice', 'bound', 'sure', 'destruction', 'closed', 'sight', 'letter', 'town', "it's", 'lay', 'as', 'went', 'carried', 'every', 'weapon', 
         'tells', 'him', '"i\'m', 'like', 'lit', 'stick', 'dynamite', 'blow', 'down."', 'lot', 'clock', 'whatever', "you've", 'past', 'point', 'figure', 
         "what's", 'mouth', 'taste', 'trouble', 'broken', 'figures', "can't", 'got', 'wash', 'hands', 'write', 'mr.', 'kind', 'because', 'em', 'behind', 
         'bars', 'tomorrow', "you'll", 'harder', 'aching', 'waking', 'breaking', 'throwing', 'chains', 'weighed', 'erase', 'final', 'fate', 'losing', 'by', 
         'any', 'definition', 'submit', 'used', 'fumble', 'move', 'lips', 'stumble', 'getting', 'awful', 'rough', 'both', 'knocked', 'around', 'takes', 
         'seat', "she's", 'blowing', 'ambitions', 'tried', 'having', 'thoughts', 'spending', 'other', 'scenes', 'boss', 'rolling', 'rubber', 'sleeves', 
         'quickly', 'lover', 'bleeds', 'knees', 'crossed', 'watch', 'another', 'reason', 'tossed', 'fifty', 'means', 'statisticians', 'songs', "we'd", 
         'perfect', 'harmony', 'would', 'wait', 'rains', 'no...', 'impressed', 'strong', 'wrong', 'guess', 'set', 'shown', 'ready', 'now.', 'hell', 'always', 
         'out.', 'sun', 'lights', 'space', 'put', 'smile', 'bad', 'fade', 'worst', 'times', 'known', 'best', 'them', 'friends', 'unto', 'end', 'hear', 
         'saying', 'please', 'everlasting', 'grace', 'eternity', 'fathers', 'voices', 'lord', "he's", 'swinging', 'holy', 'sword', 'knew', 'bought', 
         'warned', 'tries', 'yes', 'unattainable', "we'll", 'float', 'high', 'below', 'ghosts', 'dress', 'chameleon', 'wanna', 'seems', 'slow', 'ahead', 
         'abuse', 'control', 'woo-woo', '[outro', 'chorus]', 'light', 'highs', 'heavy', 'lows', 'years', 'share', 'from', 'painted', 'arched', 'ceilings', 
         'barroom', 'floors', 'disappear', 'while', 'seasons', 'begin', 'change', 'ragged', 'mile', 'crave', 'nights', 'months', 'goodbye', 'snowy', 'denver', 
         'mountains', 'bedroom', 'last', "fire's", 'weakest', 'flame', 'dying', 'rest', 'calm', 'morning', 'sunrise', 'drive', 'pours', 'window', 'floor', 
         'chest', 'grip', 'pistol', 'howling', 'dog', 'door', 'show', 'heard', 'sound', 'voice', 'missed', 'dripping', 'ink', 'pen', 'note', 'hoping', 'hit', 
         'lie', 'favorite', 'distance', 'why', 'such', 'surprise', 'talk', 'wonder', 'which', 'person', 'sad', 'song', 'somewhere', 'rhyme', 'elizabeth', 
         'boy', "isn't", 'listening', 'white', 'dress.', 'quiet', 'afternoons', 'given', 'soon.', 'hair', 'curls', 'pretty', 'uptight', 'mexican', 'girl.', 
         'shit', 'called', "isnt'", 'back', 'me.', 'wooo', 'ooooh', 'oooohh', 'string', 'silly', 'admit', 'guess.', 'dawn', 'darkness', 'once', 'twice', 
         'slice', 'here', 'none', 'wrong.', 'return', 'ask', 'disappointed', 'unexpected', 'harvest', 'kentucky', 'son', 'runs', 'farthest', 'doing', 'faith', 
         'belief', 'except', 'teeth', 'champions', 'rust', 'rot', 'breathing', 'missing', 'passing', 'brush', 'strokes', 'sickness', 'folks', 'renewed', 
         'unchanging', 'pasture', 'fenced', 'edge', 'dakota', 'thunder', 'raging', 'shoes', 'feet', 'grass', "we've", 'laid', 'above', 'tunnel', 'under', 
         'inside', 'alive', 'everybody', 'knows', 'job', 'costs', 'shy', 'moves', 'never-ending', 'desire', 'calcified', 'lose', 'unspeakable', 'denial', 
         'his', 'crimes', 'versatile', 'raining', 'sea', 'follow', 'shaking', 'speak', 'winter', "pourin'", 'new', 'fine', 'journey', 'thru', 'going', 'till', 
         'february', 'comes', 'fiddler', 'drum', 'walk', 'bleak', 'halls', "architect's", 'un-imagination', 'returning', 'venue', 'where', 'held', 'very', 
         'conversation', 'friend', 'arrived', 'early', 'swanned', 'later', 'changed', 'nod', 'order', 'double', 'mixer', 'leaving', 'oh-oh-oh-oh', 'told', 
         "playmate's", 'successful', 'handsome', 'charming', 'damn', 'wound', 'harming', 'joking', 'rudely', 'interrupted', 'half-wit', 'boyfriend', 'beat', 
         'forget', 'were', "'cause", 'dreamed', 'road', "'93", 'over', 'woah', 'low', 'smoke', 'hand', 'lying', 'awake', 'hotel', 'valley', 'pray', 'picks', 
         'bones', 'guitar', 'louder', 'anymore', 'tired', 'ran', 'streets', 'forever', 'arm', 'setting', 'higher', 'perfection', 'wrote', 'book', 'hid', 
         'page', "didn't", 'locked', 'cage', 'novel', 'likes', 'started', 'word', 'rare', 'fragile', 'bird', "couldn't", 'spell', 'table', 'sky', 'cold', 
         'apple', 'story', 'proper', 'hello', "haven't", 'felt', 'warm', 'today', 'signs', 'hero', 'tale', 'truly', 'prevail', 'sequel', "part's", 'die', 
         'movie', 'tragic', 'grey', 'short', 'roads', 'smooth', 'wanderings', 'bring', 'wisdoms', 'gold', 'most', 'matter', 'happiness', 'lasting', 'real', 
         'purify', 'passions', 'river', 'wet', 'stretch', 'paws', 'along', 'shores', 'gaze', 'depths', 'crouch', 'spiders', 'raindrops', 'singing', 'ghost', 
         'reverie', 'cuz', 'miss', 'hollow', 'stallion', 'nightmares', 'armistice', 'stalk', 'gibberish', 'moon', 'different', 'language', 'cannot', 'after', 
         'june', 'pine', 'brushing', 'dew', 'unlike', 'copious', 'death', 'precipitation', 'carry', "something's", 'pending', 'curvaceously', 'sunburned', 
         'agree', "should've", "pleasure's", 'chin', 'mess', 'pool', 'spent', 'sunday', 'school', 'july', 'golden', 'hue', 'hung', 'drove', 
         'straight', 'burial', 'ground', 'saw', 'loud', 'gray-blue', 'grave', 'red', 'suits', 'five', 'took', '405', 'act', 'age', 'fast', 'asleep', 
         'choose', 'midnight', 'kitchen', 'pocketbook', 'quit', 'hate', 'anyway', 'another...', 'shift', 'safety', 'pride', "one's", 'keeping', 'score', 
         'fear', 'downfall', 'enemy', 'blame', 'fault', 'core', 'leap', 'corners', 'somersault', 'emotions', 'dive', 'steady', 'crash', 'lies', 'nice', 
         'right', 'theyâ€…marked', 'woodenâ€…cross', 'gal', "'sorry", "loss'", 'ended', 'saturday', 'showdown', 'caught', 'fire', 'wish', 'safe', 'hits', 
         'bottle', 'sits', 'weak', 'stand', 'saint', 'paula', 'rainy', 'girl', 'skies', 'memory', 'swimming', 'infinity', 'sometimes', 'falling', 'everywhere', 
         'black', 'wire', 'sings', 'blue', 'following', 'cloud', 'hot', 'somethins', 'mother', 'father', 'cut', 'jesus', 'stronger', 'wind', 'rollin', 'hopin', 
         'comin', 'late', 'blinded', 'relates', 'loathsome', 'sounds', 'texas', 'funerals', 'breakin', 'somehow', 'feels', 'im', 'brain', 'fried', 'griddle', 
         'cant', 'beggin', 'rain', 'losin', 'guts', 'split', 'howlin', 'feedin', 'petunia', 'cmon', 'prowlin', 'crawlin', 'gotta', 'lonesome', 'couldnt', 
         'straw', 'seen', 'whisper', 'whos', 'taken', 'well-earned', 'reward', "takin'", 'shadow', 'errors', 'steal', "placin'", 'path', 'touch', 'letting', 
         'pleases', 'crime', 'crushed', 'bone', 'spoken', 'sweeter', 'yesterday', 'abiding', 'anything', 'claim', 'victory', 'surrender', 'without', 'died', 
         'cross', 'rose', 'yours', 'radiant', 'glorious', 'remain', 'mystery', 'mysteries', 'heaven', 'enshrined', 'nighthawk', 'diner', 'blueberries', 
         'cinnamon', 'cup', 'coffee', 'cream', 'fuel', 'cigarette', 'reading', 'instruction', 'manual', 'everyday', 'further', 'start', 'consider', 'desired', 
         "wasn't", 'bit', 'umpire', "else's", 'sweat-faced', 'counter', 'half-regretting', 'flyer', 'watching', 'silver', 'soda', 'underneath', 'ceiling', 'fan', 
         'half-consumed', 'perspire', 'tendency', 'laugh', 'moments', 'silent', 'type', 'exit', 'sign', 'yellow', 'brick', 'dirty', 'dishes', 'til', 'miles', 'each', 
         'future', 'holds', 'surface', 'storm', 'sunset', 'hurricane', 'feeling', 'clearly', 'nearly', 'heal', 'fades', 'loves', 'feelings']

context = {"On my bed she said i'm just another" : ["That said i have been a fool", "Just like me you'd pull me she said"],
           "That said i have been a fool" : ["On my bed she said i'm just another"],
           "Just like me you'd pull me she said" : ["On my bed she said i'm just another"],
           "She said we'd live in love darling" : ["He says we're going everywhere together"],
           "He says we're going everywhere together" : ["She said we'd live in love darling", "Walls i'd climb to hold you say what"],
           "You say what you oh-oh-oh-oh oh-oh-oh-oh oh-oh-oh-oh" : ["Walls i'd climb to hold you say what"],
           "Walls i'd climb to hold you say what" : ["You say what you oh-oh-oh-oh oh-oh-oh-oh oh-oh-oh-oh"],
           "Your restless little boy and every morning sunrise" : ["I know it takes a little boy"],
           "I know it takes a little boy" : ["Your restless little boy and every morning sunrise"],
           "You don't wanna get lost i've been" : ["Been lost but oh oh no longer lost", "And dont i know i am lost"],
           "Been lost but oh oh no longer lost" : ["You don't wanna get lost i've been"],
           "And dont i know i am lost" : ["You don't wanna get lost i've been"],
           "Leaving it up the words ive lost" : ["And dont i know i am lost", "Been lost but oh oh no longer lost"],
           "Wanna remember who i've been who i've lost" : ["And dont i know i am lost"],
           "Oh lying awake in your mind everybody knows" : ["That you used to be in your mind"],
           "Trying to meet you always been who i've" : ["Trying to roll through it all"],
           "Trying to roll through it all" : ["Trying to meet you always been who i've"],
           "I dont i keep trying to be" : ["Trying to roll through it all"],
           "But i pray something clearly gone baby please" : ["Im so much older baby please"],
           "Im used to say it should've been" : ["It should've been me something picks me", "Wanna heal but it should've been lonesome"],
           "I haven't been me nothing without you" : ["I haven't been me go now"],
           "I haven't been me go now" : ["I haven't been me nothing without you"],
           "It should've been me something picks me" : ["Im used to say it should've been"],
           "Wanna heal but it should've been lonesome" : ["Im used to say it should've been"],
           "Ain't it up leaving it should've been" : ["Im used to say it should've been"],
           "Im used to you gotta do you" : ["Im used to you wanna remember who"],
           "Im used to you wanna remember who" : ["Im used to you gotta do you"] }

generated_lines = ["Im used to say it should've been", "And dont i know i am lost", "I can feel you hope mine's not", "To tell me i dont wanna stop", 
                                         "I haven't felt this in my mind", "This is up in your chameleon skin", "Your pocketbook can't hear he's handsome and unprepared", 
                                         "When i give me down and carry on", "All my dreams i can do nothing without", 
                                         "And even when i haven't been me", "If this is this go by my side", "A damn good job everybody likes", "You and i can't get used", 
                                         "Remember who i've already shown that i am", "Been lost but oh oh no longer lost",
                                         "I know that song and i know", "My love in my hand oh", "Don't follow what i know what pleases me", "Its hot and we'll keep putting stones on", 
                                         "Wanna remember who i've been who i've lost", "I will i still got your throne", "She says that you will close down", 
                                         "We drink of all that i won't be", "My love my tries to fly away", "That said i have been a fool", "On my bed she tells him it's", 
                                         "Already done wrong and some call his name", "I haven't been me nothing without you", "Don't wanna remember who i've already past", 
                                         "And i am unchanging i'm getting further", "Your restless little boy and every morning sunrise", "Wanna heal but it should've been lonesome", 
                                         "All lies crash into my chest like it", "My wings i will i know it", "Im so much older baby please", 
                                         "I haven't been me go now", "My emotions i'm waking up leaving it", "End of my love to love in reverie", "Im used to you wanna remember who", 
                                         "The floor hold you from the core", "You are warm today dont wanna heal", "When you're impressed that i know what", 
                                         "Will risk our eyes and take the life", "I know it takes a little boy", "Love oh i will close down and all", 
                                         "We are sad songs that i could blow", "This was wrong and i forget the miles", "Just like me you'd pull me she said", 
                                         "Baby dead like me i wish i watch", "On my bed she said i'm just another", "Know what you take oh oh no this", 
                                         "Know it was dead like you are radiant", "You only known love you're gonna lie", "I dont i keep trying to be", 
                                         "That showed you i don't really know oh", "You say what you oh-oh-oh-oh oh-oh-oh-oh oh-oh-oh-oh", "I show me time to be", 
                                         "It should've been me something picks me", "I already know what i will love", "You keep putting stones on the weakest", 
                                         "Try to meet somebody i will i will", "Wooo oooohh i can i love you", "As i still think i call goodbye", "Why oh oh oh lying awake", 
                                         "The fray weight of iron skin", "My eyes that's all of all", "Act my baby dont wanna hear the fuck", "I'd climb these songs are the best", 
                                         "But i pray something clearly gone baby please", "When i know i feed off the best", "All i hear he went she hides her", 
                                         "When i feel the love you have played", "Will come pourin' down it's in the darkness", "Gal 'sorry for me that i don't give", 
                                         "She said we'd live in love darling", "Your new home maybe in a boat", "Truth is nothing i love release my emotions", "The love comes up leaving it", 
                                         "Up in the line i'll do wrong", "He says we're going everywhere together", "To the downfall it's in my wings", "You don't even want to see you", 
                                         "My wings i dont wanna get used", "In the signs i dont wanna remember", "This is nothing i speak hoping that its", 
                                         "Trying to meet you always been who i've", "Just like an ocean keep raindrops off ambitions", "Im used to you gotta do you", 
                                         "Walls i'd climb to hold you say what", "Sun fried up her face just run", "Oh oh no one's keeping score no one's", "That you used to be in your mind", 
                                         "Everyday i'm getting knocked around for a string", "Oh lying awake in your mind everybody knows", "Are dead cuz i surrender i saw you", 
                                         "Too tired i'm everyday i'm a surprise", "And water my love and soul", "A empty bed and young love's forgot", "To hold my head i'm losing it", 
                                         "Leaving it up the words ive lost", "Baby dont wanna get off my saving parachute", "We never make you and take you", "You don't wanna get lost i've been", 
                                         "I can make you choose to me", "Ain't it up leaving it should've been", "Trying to roll through it all", "Your face just loved enough of my bedroom", 
                                         "Up leaving it as the end oh how", "Do this in love release my fathers face", "Gonna lie low smoke with me rainy girl", "Older mama its out and we're old enough", 
                                         "Love you keep putting stones on the night", "I know it's in your name", "The calm we held that youd be", "The showdown caught up leaving it costs", 
                                         "I will take another whisper i know", "The core if you be the skies", "I show it he says we're both", "Your only call you won't be", 
                                         "Baby that's all the winter rains come", "Theres something wrong i hear you right now", "Dont i still be running under my baby", "But i guess did he isn't up", 
                                         "On my name and in my heart", "Oh lying awake my mind will awake", "Of sunday school july has clearly gone wherever", "Of your pride on my bones i've been", 
                                         "And all for the past the hearts", "You now its time for the bars", "To say is no longer an ocean", "Know oh oh oh why do now", "Your name and i'll just say it", 
                                         "As soon as i dont wanna remember who", "Say it up leaving it oh soon", "Can i am i am i rare", "I can feel you hope mine's not", "You just give me up leaving it", 
                                         "Im used to change you've lost", "Im so caught up on mine", "Of all i guess we're going everywhere together", "Down the love i know i know it", 
                                         "She said we'd live in love darling", "Nothing had said theyre warmer than bone", "And as your leaving it oh oh", "And she's having to fly away everyday", 
                                         "Man will keep trying to be lasting", "Don't give me a smile its hopeless", "Just give me and like me it feels", "She says they say but you make love", 
                                         "And even when i haven't been me", "When your whole i'm there never knew that", "Up leaving it up to see her", "Dont wanna remember who i've been dress me", 
                                         "Know what your just a golden hue", "And quit as you left it up", "From the snowy denver mountains to me", "The loves gone and i'm not", 
                                         "Crimes are not even a taste of me", "Dynamite i am a journey thru the missing", "So your around oh darling i am", "Be right youre comin home i call", 
                                         "Will stay with spiders to be tamed", "Be good to say what pleases me", "And i arrived there never known love", "When we both know what i am unchanging", 
                                         "Archers never make me know it's mine", "She can be mine but you keep trying", "She tells him it's not alone it's", "Dont i will do nothing wrong", 
                                         "In my love you are warm", "Oh oh oh no you're on your sun", "Like it oh why why you right by", "Oh oh oh pray something bout your love", 
                                         "It's a pine with arms brushing off ambitions", "Know i drove straight down fuck it", "It started pretty uptight for us", 
                                         "Oh my saving parachute your safety fall", "Oh lying awake in his mind now", "But oh darling down in the past", "I'll never known the truth oh no i'll", 
                                         "You took some things ive done something", "A long time these quiet afternoons ", "That i lost in the end of june", "She tried to see sits alone it's better", 
                                         "On your pride on your chameleon skin", "Sun will return don't follow what i don't", "This world slow down in the streets", "Love is broken your feet ive lost", 
                                         "Of an exit sign or a novel", "In my time i'm going everywhere", "You don't know that i know what", "Everyday i'm getting right next to be mine", 
                                         "Woman dreaming of my love i can't", "I can feel you hope mine's not", "You're on my hand oh oh hello ", "Your paws along her rubber sleeves", 
                                         "Memories stored up leaving it everyday i'm not", "Say what to fly away from her shores", "Trying to be good and a little louder", "Up to sleep i read a different language", 
                                         "A dream that you love comes baby", "The lights up we tell him it's", "Your used to god i'm gonna come", "I won't be there for a foool", "You call you hate so why", 
                                         "You know it's tragic but i know", "You'd better if i loved you anymore woah", "Leaving it even when you hope", "Baby was coming up leaving it wasnt hard", 
                                         "Boarding soul and all broken figures have gone", "All these arms baby dead like me", "She said we'd live in your word", "And so caught up leaving it", 
                                         "Im so weak wish my baby was", "I know what i call me", "Blind in the line i'll be in", "Some things in my chin held shut", "Stuck on my side when you stay", 
                                         "She said we'd live in your word", "Dead like the miles we always try", "All these arms baby woah i'm older", "Dakota thunder raging and im used", 
                                         "Oh oh how much more than bone", "Hear you left it and youre in", "Say it was a letter and start", "Wanna get her depths stretch your neck", 
                                         "But oh no longer old enough yeah", "When i can't take you home 'cause sunburned skin", "Lights go get stuck in my mind", "When i ain't sleeping mama when you won't", 
                                         "Hopin that i will know there's nothing", "My love stick around for you leaving", "Afternoons she don't give me oh dead", "For the path of an apple i love", 
                                         "All these arms like me darling i know", "All night all goes to me gone wherever", "I've given up leaving it was gonna lie", "All goes to the core if i am", 
                                         "And sound in the worst way", "You keep putting stones on my emotions", "In perfect harmony if i know it", "And calm we drink dirty dishes", "The note hoping that i am", 
                                         "My heart i keep trying to", "Know what you nothing without you", "Baby dont i still taste of it", "Baby maybe if you'll know youd break", "Im so why why why why ", 
                                         "You better quit as her heart is", "And she's having to fly away everyday", "Sound of a song so why do it", "So your around oh darling i am", "Of a while feel you are alone now", 
                                         "Should've been you used to me my mind", "Up to me back to say it", "That it's our stories our eyes have been", "And i can make those dice", "To you leaving it up leaving it", 
                                         "As he went she don't follow me", "Im used to me when your here", "A river till youre closer but whatever", "I can see you leaving it up", "I had never will be your words", 
                                         "A foool oh i am faith", "To me baby maybe if i guess", "In my fathers face don't follow me", "You there i know whos taken", "If youre home if you are the fire", 
                                         "The loves gone and i'm not"]

prepositions = ["a", "i", "as", "if", "your", "to", "and", "let", "my", "just", "the", "til", "of", "but", "when", "such", "in", "just", "and"]

bad_generated_lines = ["Baby maybe if what's not sunset or have", "Trying to you want me it not even", "Already past will stay then i have gone", "Stones on that i love at me everything", 
                       "Alive you will take oh darling for", "Can do me blind the love a while", "She will i hear another like me safe", "When the line lay your errors lie with", 
                       "Love confess your job everybody knows how things", "Cause everybody knows how am the world she", "Wanna get lost in a dog at", "Am dakota thunder raging and you the ceiling", 
                       "Your double and i am sleep i couldnt", "Am the son that i dont i stalk", "Early and by any good to me blind", "Your eyes and by when we always", 
                       "When your chameleon skin i may all", "For my love at me ooh peaking at", "In my heart is dying down than", "My home i know what the story", "My fathers final say that new home", 
                       "In my side i love on bending", "I aint up all of trying", "Of love you hold all the past five", "On the lies crash into my guitar so", "Be tamed catch the fray weight of", 
                       "All flock together guess i'll have a lit", "Are warm the end of a gamble baby", "Are love songs let your things are called", "Are warm today i heard the fray weight", 
                       "Can and i created in the passing seasons", "And take the blues have gone", "The months quickly as the sound", "You stood beneath the ground baby was", 
                       "Already loved enough to the days are love", "Never make me time she don't and", "If you'd better your love stick around for", "Life of my little why why why why", 
                       "Of me up leaving it oh oh why", "What you've shown it out til the things", "But you feels like you were dead like", "Up sometime you try i know what", 
                       "That it's been me oh somethins father", "Its the ones and if i don't care", "Are sad songs that you are wrong. none", "Even spell on the best guess. i love", 
                       "On love you in her salty memories stored", "You to grieve and your lips on", "It should've been shy and hes stuck", "In my mind somersault into the lies", 
                       "Im so go get prowlin i pray", "It costs everybody knows that holy sword", "My love you talk to see sits", "That i saw you away and warned", 
                       "Of my favorite songs are warm and warned", "Say to say it will be tamed she", "Boarding soul sell the end of it didn't", "It's better left it up leaving it up", 
                       "If you when you my means and some", "It out who i've found you away", "I know what to say it up", "That day will you missed me only known", "Know i know what the one thing that", 
                       "Wrong and we're living is calcified the ceiling", "Your eyes and in your breath is no", "Still be got on my home just loved", "No one's fault cause the year but", 
                       "When you nothing without you desired wasn't this", "Even want to my shoes and left there", "It oh dead like me safe", "In the dive ocean keep hell you", 
                       "My cheek conveniency you said i'll never", "It the farthest i could stand on", "My mind or have a song sounds", "Never make of a surprise when i'm getting", 
                       "Is just say goodbye to see that about", "Song elizabeth i bet youd break your wanderings", "Long you from the trouble broken figures that", 
                       "Mile long you lord i will return don't", "Love sometimes when i'm so beat my side", "Your things we will not over yet", "Girl the miles we are all your lips", 
                       "Why do nothing i still be that showed", "Why a taste like me fuck is coming", "Have played the nights while should call", "What the lights up hey i'll never was", 
                       "Everyday i'm not be right up to be", "Im so i hear me dripping from", "In my emotions i'm everyday i'm blowing", "A dream on my baby was before", 
                       "And cinnamon cup of sight left town", "I surrender i knew me back", "A cage wrote a while when", "Of times never own we drive never met", 
                       "Am dakota thunder raging and now its share", "Even when i'm falling next to put you", "Going back to be my baby you used", "Say but you if i miss you will", 
                       "Are radiant glorious the lies i don't really", "Your name think about the door to", "As the words are warm today i think", "The umpire in the dive ocean", 
                       "And you for a tendency to", "You are sad songs that you", "To be harder to fly head ive", "And gaze into everything don't mean", "The roads that said that never will", 
                       "And fragile bird that i throw those", "Of my mind somersault into my love is", "One love you to find me it won't", "If you the love comes up leaving it", 
                       "Up i'll just give me its proper end", "Of my cheek conveniency you will i can", "As can see you keep putting stones on", "Wonder if nothing without you can't you hear", 
                       "Try i don't care if you 'til you're", "Your mind somersault into everything they should there", "Away but i can you know that she", "Say is breaking out jesus make you", 
                       "Can let you best where we held that", "We dreamed a tendency to hold you wisdoms", "In on a blunder young love em", "To hold you are wrong and", "My mind somersault into my love", 
                       "The valley down it's no longer an", "In the way to you home trying", "It out i'm going everywhere together guess", "Love you leave reason tossed about hopeless", 
                       "That it's just let us warm the kitchen", "Your sun fried up leaving it up we", "All i will come for gin me", "Guess i'll have been there is hard", 
                       "Old song put my saving parachute your half-wit", "Hope at the weakest flame is that", "Trying to the road you don't even want", "Ever been you don't mean to the love", 
                       "When i'm not be long time just seems", "When the way down and i will risk", "And sing ive made i am old", "To me here none are the valley", "I am the inside how much it", 
                       "A journey thru the sky copious with", "The ground i speak with a cocoon", "That's all statisticians that you canâ€…seeâ€…right through it", 
                       "All statisticians that maybe if this through oh", "Love sometimes when the ground baby dead", "Said all your feet and your pride on", "All these days so beat a job everybody", 
                       "Im so i used to make those", "A ragged mile long time she hits", "Up leaving it up leaving it even want", "If you been and quit sweat-faced counter woman", 
                       "Baby someplace down as you when the words", "Have a boat to come but i've found", "At all i have played wherever i alive", "Leaving it up leaving it again and sound", 
                       "Up leaving it pours into her depths", "Theres something that as i rose with", "Im so why you wisdoms which you", "To you move slow down than bone", 
                       "You theres a boss she's had ever", "I couldnt take your restless little louder", "In the streets are love you now", "Said that weighed me i feast on", 
                       "When i'm sickness come for me it up", "Is my skin i haven't felt this go", "When we dreamed a farse young in", "When i will stay and he's swinging that", 
                       "Baby was inside my soul and on", "All i understood that cross i found so", "Surrender i will stay all statisticians that you", "All the ink of the shore crash into", 
                       "Call me safe and i know it up", "That its the fray weight of your half-wit", "Love the wine we drive never known", "Snowy denver mountains to my gal 'sorry for", 
                       "Is nothing had never known love comes baby", "To you heard you falling next", "The fiddler to say but you home", "To grieve and i watch those from", 
                       "We tell him it's no this through", "Who are called the most anything as you", "Love darling i can walk you i was", "Off the bars close down at times can", 
                       "Window i know archers never own and", "On mine on my truth will be tamed", "Up placin' the middle of them only known", "You choose to my hand reading some", 
                       "A worm spins a river hopin that", "My wings dime store penny shore waiting", "It could blow you can and we're", "My mind leaving it was coming up", 
                       "To you better if you can", "Too much later as ghosts dress i ever", "Know i already past will not the wine", "Than fight and you leap inside how can", 
                       "On your fast asleep and head should there", "That its the blues have you mr kind", "When you nod at your arrows sing ive", "Know what to say you're so let it", 
                       "When everything and room service babe me dripping", "For the game send out loud was woah", "Give me i will you said it's about", "Older too anna muse oh oh how much", 
                       "All your bed i live to see lord", "The grass we've laid above i aint", "My skin i never ours archers never", "And grey i surrender i we never", 
                       "When i am lost a boat to consider", "Go by my wings i know it she", "What you wanna disappear my own and", "This years had said that it the snowy", 
                       "Anything as her shores and stumble when you", "Wherever i've lost inside how am dakota thunder", "She carried off ambitions that you some fight", 
                       "Oh somethins mother if what's not over yet", "Some instruction manual you somehow well it not", "Know it out til the sky copious with", "Am old we drive never own i know", 
                       "Inside how am back to hold you can't", "Baby dont i still a taste of it", "Wine we never will awake with me she", "By we'll float high and sound in love", 
                       "The time for gin me it up", "Say but my heart in a mexican girl", "Aching now hes coming up older too", "Be that as you to my little bit", "All i have wound up the ground baby", 
                       "Know and now they're starting to you", "Truth will you just a vincent van gogh", "Done that never will not hard to spain", "About through the edge i wonder which person", 
                       "Been me and cinnamon cup of this on", "An art her shores and further and she's", "In the year but i think about", "My cheek conveniency you lord there is", 
                       "Are not see you used to show it", "On mine steady to spain wherever i have", "Just before and dont wanna get wet stretch"]